### ISSUE TITLE
requests.exceptions.HTTPError: 400 Client Error: Expect type list

### ISSUE THREAD

**Issue by medmaca** [biothings/biothings_client.py#17] opened 2021-02-22 17:12 UTC
The simple script

```
from biothings_client import get_client
gene_client = get_client('gene')
results = gene_client.querymany(['P24941', 'O14727'], scopes='uniprot', fields='symbol,name')
print(results)
```

Results in the following error:
>>> from biothings_client import get_client
>>> gene_client = get_client('gene')
>>> results = gene_client.querymany(['P24941', 'O14727'], scopes='uniprot', fields='symbol,name')
querying 1-2...Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nobackup/bioinfo_share/software/anaconda2/envs/py27_dev/lib/python2.7/site-packages/biothings_client/base.py", line 542, in _querymany
    for hits in self._repeated_query(query_fn, qterms, verbose=verbose):
  File "/nobackup/bioinfo_share/software/anaconda2/envs/py27_dev/lib/python2.7/site-packages/biothings_client/base.py", line 223, in _repeated_query
    from_cache, query_result = query_fn(batch, **fn_kwargs)
  File "/nobackup/bioinfo_share/software/anaconda2/envs/py27_dev/lib/python2.7/site-packages/biothings_client/base.py", line 541, in query_fn
    def query_fn(qterms): return self._querymany_inner(qterms, verbose=verbose, **kwargs)
  File "/nobackup/bioinfo_share/software/anaconda2/envs/py27_dev/lib/python2.7/site-packages/biothings_client/base.py", line 488, in _querymany_inner
    return self._post(_url, params=_kwargs, verbose=verbose)
  File "/nobackup/bioinfo_share/software/anaconda2/envs/py27_dev/lib/python2.7/site-packages/biothings_client/base.py", line 176, in _post
    res.raise_for_status()
  File "/nobackup/bioinfo_share/software/anaconda2/envs/py27_dev/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Expect type list. for url: http://mygene.info/v3/query/
>>> print(results)
[{u'query': u'"P24941","O14727"', u'notfound': True}]

I've used mygene python API for a number of years without a hitch, existing scripts that have worked now throw this error.  Any help would be massively appreciated.

**Comment by newgene** [comment] 2021-02-22 21:28
@medmaca This can be a temporary fix for now before we release a new version to resolve this issue:

```
pip install biothings_client==0.2.2
```

**Comment by dhimmel** [comment] 2021-02-22 21:43
Also experiencing this issue (noticed it today).

@newgene can you comment more on the cause of the problem?

> release a new version to resolve this issue

Another option might be reverting the change that caused the latest version of biothings-client (v0.2.3) to fail until a version of biothings-client is released without the issue?

**Comment by namespacestd0** [comment] 2021-02-22 23:53
The server update over the weekend addressed a few reliability issues along with formalizing the additional support for a few request content types. Previously, we did not differentiate the request content type of JSON, form-encoded, or URL parameters, thus having our client sending POST data in string serialized individual fields to represent lists. Now, that type of content needs to be sent via the form data type. Application/JSON body should use lists to represent lists, instead of a comma separated list. The update in our client updated the calling signature to match this change. It has been published now.

**Comment by dhimmel** [comment] 2021-02-23 01:14
> The update in our client updated the calling signature to match this change. It has been published now.

Thanks @namespacestd0  for the info. So this issue is fixed by aa9a9a4dbfa8daa0952b24fe168daad5cb3e8958 and released in v0.2.4?

**Comment by namespacestd0** [comment] 2021-02-23 01:24
Yes that's right.

**Comment by medmaca** [comment] 2021-02-23 09:37
Thanks for turning this around so quickly.  With v0.2.4 everything appears to working now.

**Comment by newgene** [comment] 2021-02-23 17:22
For anyone looks for this issue to resolve this recent biothings_client error, please upgrade your local `biothings_client`:

```
pip install biothings_client -U
``` 

Thanks @medmaca and @dhimmel for your prompt reporting.

**Closed by newgene** 2021-02-23 17:22 UTC

**Comment by newgene** [comment] 2021-02-25 23:00
Just fyi, we have released another new version of biothings_client today: [v0.2.5](https://pypi.org/project/biothings-client/#history), which should handle similar issues which might happen on other query parameters.
